version: '3'

services:

  api:
    image: davisegundo88/openweatherapi:main
    container_name: openweatherapi
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL_CONNECT: mongodb://mongo:27017/test

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"


    